sudo: required
services:
  - docker
before_install:
  - docker build -t nanditau/docker-react:DEV -f Dockerfile.DEV .
script:
  - docker run -e CI=true nanditau/docker-react npm test -- --coverage
language: generic
  
